services:
  sonar:
    image: ${DOCKER_REGISTRY-}sonar
    container_name: sonar-app
    build:
      context: .
      dockerfile: Sonar/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=sonardb;UserName=sonaruser;Password=sonarpass"